import Jacobian.Periods.ChartBallAtPoint
import Jacobian.Periods.ChartLiftApply
import Jacobian.Periods.ChartLiftBoundary
import Jacobian.Periods.ChartLiftReflSubpath
import Jacobian.Periods.ChartLiftSymm
import Jacobian.Periods.DivFinIcc
import Jacobian.Periods.ChartedForm
import Jacobian.Periods.ChartedFormSmul
import Jacobian.Periods.ChartedFormPullback
import Jacobian.Periods.ChartedFormPullbackApply
import Jacobian.Periods.ChartedFormPullbackApplyLinear
import Jacobian.Periods.ChartedFormPullbackLinearMap
import Jacobian.Periods.ChartedFormPullbackLinearMapApply
import Jacobian.Periods.ChartedFormPullbackLinearMapApplyLinear
import Jacobian.Periods.ChartedFormPullbackLinearMapSimp
import Jacobian.Periods.ChartedFormPullbackLinearMapSmul
import Jacobian.Periods.ChartedFormPullbackSimp
import Jacobian.Periods.ChartedFormPullbackSmul
import Jacobian.Periods.ChartedFormPullbackSub
import Jacobian.Periods.ChartedFormPullbackCurveIntegrable
import Jacobian.Periods.ChartedFormSimp
import Jacobian.Periods.IntegralOneCycle
import Jacobian.Periods.HomTorsionVanishing
import Jacobian.Periods.LebesgueChartRadius
import Jacobian.Periods.PathIntegralChart
import Jacobian.Periods.ChartedFormApplyLinear
import Jacobian.Periods.ChartedFormCurveIntegrable
import Jacobian.Periods.ChartedFormLinearMap
import Jacobian.Periods.ChartedFormLinearMapApply
import Jacobian.Periods.ChartedFormLinearMapApplyLinear
import Jacobian.Periods.ChartedFormLinearMapSimp
import Jacobian.Periods.ChartedFormLinearMapSmul
import Jacobian.Periods.ChartedFormSub
import Jacobian.Periods.PathIntegralChartAdd
import Jacobian.Periods.PathIntegralChartApply
import Jacobian.Periods.PathIntegralChartLinear
import Jacobian.Periods.PathIntegralChartNegSymm
import Jacobian.Periods.PathIntegralChartSub
import Jacobian.Periods.PathIntegralChartCorrect
import Jacobian.Periods.PathIntegralChartCorrectApply
import Jacobian.Periods.PathIntegralChartCorrectAdd
import Jacobian.Periods.PathIntegralChartCorrectLinear
import Jacobian.Periods.PathIntegralChartCorrectNegSymm
import Jacobian.Periods.PathIntegralChartCorrectSub
import Jacobian.Periods.PathIntegralChartCorrectSmul
import Jacobian.Periods.PathIntegralChartCorrectSimp
import Jacobian.Periods.PathIntegralViaChartCorrectSmulSymm
import Jacobian.Periods.PathIntegralChartCorrectSmulSymm
import Jacobian.Periods.PathIntegralChartSmulSymm
import Jacobian.Periods.PathIntegralViaChartSmulSymm
import Jacobian.Periods.PathIntegralViaChartCorrectSymmAddSelf
import Jacobian.Periods.PathIntegralViaCoverSymmAddSelf
import Jacobian.Periods.PathIntegralChartCorrectSymmAddSelf
import Jacobian.Periods.PathIntegralChartSymmAddSelf
import Jacobian.Periods.PathIntegralViaChartSymmAddSelf
import Jacobian.Periods.PathIntegralChartCorrectTrans
import Jacobian.Periods.PathIntegralChartTrans
import Jacobian.Periods.PathIntegralViaChartCorrectNegSymmEqSelf
import Jacobian.Periods.PathIntegralViaCoverNegSymmEqSelf
import Jacobian.Periods.PathIntegralChartCorrectNegSymmEqSelf
import Jacobian.Periods.PathIntegralChartNegSymmEqSelf
import Jacobian.Periods.PathIntegralViaChartNegSymmEqSelf
import Jacobian.Periods.ChartLiftTrans
import Jacobian.Periods.ChartLiftTransApply
import Jacobian.Periods.PathIntegralViaChartCorrectTrans
import Jacobian.Periods.PathIntegralViaChartCorrectSmulSymmEqNegSmul
import Jacobian.Periods.PathIntegralViaCoverSmulSymmEqNegSmul
import Jacobian.Periods.PathIntegralChartCorrectSmulSymmEqNegSmul
import Jacobian.Periods.PathIntegralChartCorrectNegSmul
import Jacobian.Periods.PathIntegralViaChartCorrectNegSmul
import Jacobian.Periods.PathIntegralViaCoverNegSmul
import Jacobian.Periods.PathIntegralChartNegSmul
import Jacobian.Periods.PathIntegralViaChartNegSmul
import Jacobian.Periods.PathIntegralViaChartCorrectNegSmulSymmEqSelf
import Jacobian.Periods.PathIntegralViaCoverNegSmulSymmEqSelf
import Jacobian.Periods.PathIntegralChartCorrectNegSmulSymmEqSelf
import Jacobian.Periods.PathIntegralChartNegSmulSymmEqSelf
import Jacobian.Periods.PathIntegralViaChartNegSmulSymmEqSelf
import Jacobian.Periods.PathIntegralChartCorrectSmulSmul
import Jacobian.Periods.PathIntegralViaChartCorrectSmulSmul
import Jacobian.Periods.PathIntegralViaCoverSmulSmul
import Jacobian.Periods.PathIntegralChartSmulSmul
import Jacobian.Periods.PathIntegralViaChartSmulSmul
import Jacobian.Periods.PathIntegralChartCorrectNegEqNegOneSmul
import Jacobian.Periods.PathIntegralViaChartCorrectNegEqNegOneSmul
import Jacobian.Periods.PathIntegralViaCoverNegEqNegOneSmul
import Jacobian.Periods.PathIntegralChartNegEqNegOneSmul
import Jacobian.Periods.PathIntegralViaChartNegEqNegOneSmul
import Jacobian.Periods.ChartedFormPullbackApplyApplyLinear
import Jacobian.Periods.ChartedFormPullbackLinearMapApplyApplyLinear
import Jacobian.Periods.ChartedFormApplyApplyLinear
import Jacobian.Periods.ChartedFormLinearMapApplyApplyLinear
import Jacobian.Periods.PathIntegralViaCoverOneSmul
import Jacobian.Periods.PathIntegralViaChartCorrectOneSmul
import Jacobian.Periods.PathIntegralChartCorrectOneSmul
import Jacobian.Periods.PathIntegralChartOneSmul
import Jacobian.Periods.PathIntegralViaChartOneSmul
import Jacobian.Periods.PathIntegralViaCoverPickOneSmul
import Jacobian.Periods.PathIntegralViaCoverPickNegEqNegOneSmul
import Jacobian.Periods.PathIntegralViaCoverPickSmulSmul
import Jacobian.Periods.PathIntegralViaCoverPickNegSmul
import Jacobian.Periods.ChartedFormPullbackEqChartedFormCompMfderiv
import Jacobian.Periods.ChartedFormPullbackEqChartedFormOfMfderivId
import Jacobian.Periods.PathIntegralInChartCorrectEqOfMfderivId
import Jacobian.Periods.PathIntegralViaChartCorrectEqOfMfderivId
import Jacobian.Periods.CoverSegmentSubpathRange
import Jacobian.Periods.PathIntegralViaCoverWithEqOfMfderivId
import Jacobian.Periods.PathIntegralViaCoverEqOfMfderivId
import Jacobian.Periods.ChartedFormPullbackEqChartedFormOfSymmEventuallyEqId
import Jacobian.Periods.ChartedFormPullbackRefl
import Jacobian.Periods.PathIntegralReflChart
import Jacobian.Periods.PathIntegralReflCover
import Jacobian.Periods.MfderivTranslation
import Jacobian.Periods.ChartedFormPullbackTranslationChart
import Jacobian.Periods.PathIntegralTranslationChart
import Jacobian.Periods.ChartedFormPullbackLinearMapEqOfMfderivId
import Jacobian.Periods.TranslationChart
import Jacobian.Periods.ChartedFormPullbackEqOnOfMfderivId
import Jacobian.Periods.PathIntegralChartSmulSymmEqNegSmul
import Jacobian.Periods.PathIntegralViaChartSmulSymmEqNegSmul
import Jacobian.Periods.PathIntegralChartCorrectZero
import Jacobian.Periods.PathIntegralViaChartAdd
import Jacobian.Periods.PathIntegralViaChartApply
import Jacobian.Periods.PathIntegralCongr
import Jacobian.Periods.PathIntegralSegmentSymm
import Jacobian.Periods.PathIntegralViaChartLinear
import Jacobian.Periods.PathIntegralViaChartNegSymm
import Jacobian.Periods.PathIntegralViaChartSub
import Jacobian.Periods.PathIntegralViaChartCorrect
import Jacobian.Periods.PathIntegralViaChartCorrectAdd
import Jacobian.Periods.PathIntegralViaChartCorrectApply
import Jacobian.Periods.PathIntegralViaChartCorrectNeg
import Jacobian.Periods.PathIntegralViaChartCorrectNegSymm
import Jacobian.Periods.PathIntegralViaChartCorrectSmul
import Jacobian.Periods.PathIntegralViaChartCorrectSub
import Jacobian.Periods.PathIntegralViaChartCorrectZero
import Jacobian.Periods.PathIntegralViaCover
import Jacobian.Periods.PathIntegralViaCoverNeg
import Jacobian.Periods.PathIntegralViaCoverWithAdd
import Jacobian.Periods.PathIntegralViaCoverWithApply
import Jacobian.Periods.PathIntegralViaCoverWithSub
import Jacobian.Periods.PathIntegralViaCoverPick
import Jacobian.Periods.PathIntegralViaCoverSymm
import Jacobian.Periods.PathIntegralViaCoverNegSymm
import Jacobian.Periods.PathIntegralViaCoverSmulSymm
import Jacobian.Periods.PathIntegralViaCoverPickApply
import Jacobian.Periods.PathIntegralViaCoverPickRefl
import Jacobian.Periods.PathIntegralViaCoverPickSimp
import Jacobian.Periods.PathIntegralViaCoverPickSmul
import Jacobian.Periods.PathIntegralViaCoverWithRefl
import Jacobian.Periods.PathIntegralViaCoverSmul
import Jacobian.Periods.PathIntegralViaCoverZero
import Jacobian.Periods.PathLift
import Jacobian.Periods.PathLiftSimp
import Jacobian.Periods.PathLiftSimpFromX
import Jacobian.Periods.PathReflSubpath
import Jacobian.Periods.PathSymmSubpath
import Jacobian.Periods.PathPartitionSymm
import Jacobian.Periods.PathPartitionCoverSymm
import Jacobian.Periods.PathPartitionCoverSigmaForm
import Jacobian.Periods.PathPartition
import Jacobian.Periods.PeriodFunctional
import Jacobian.Periods.PeriodFunctionalApi
import Jacobian.Periods.PeriodFunctionalIntSmul
import Jacobian.Periods.PeriodSubgroupNeg
import Jacobian.Periods.PeriodSubgroupApi
import Jacobian.Periods.PeriodSubgroupClosure
import Jacobian.Periods.PeriodSubgroupExt
import Jacobian.Periods.PeriodSubgroupRange
import Jacobian.Periods.BasisAlignedPeriodSubgroup
import Jacobian.Periods.BasisAlignedPeriodPairing
import Jacobian.Periods.BasisAlignedAnalyticJacobianEquiv
import Jacobian.Periods.PeriodLattice
import Jacobian.Periods.Polygon4g
import Jacobian.Periods.Orientable
import Jacobian.Periods.SmoothRealStructure
import Jacobian.Periods.ComplexManifoldOrientable
import Jacobian.Periods.TopologicalGenus
import Jacobian.Periods.TopologicalGenusInvariance
import Jacobian.Periods.SurfaceClassification
-- `Jacobian.Periods.AnalyticGenusEqTopologicalGenus` not re-exported here
-- because it carries a Stage B umbrella theorem
-- `JacobianChallenge.Periods.analyticGenus_eq_topologicalGenus` whose name
-- collides with the existing parallel theorem of the same fully-qualified
-- name in `PeriodFunctional.lean` (which is imported above). Both prove
-- the same statement under different hypothesis sets; consolidation is
-- a follow-up refinement. Import `AnalyticGenusEqTopologicalGenus`
-- directly where needed (e.g. from `Jacobian/Blueprint/Sec03/PolygonalModel.lean`).

/-!
# Periods infrastructure

Top-level module that re-exports the production Queue D target
files. Other modules can import `Jacobian.Periods` instead of
pulling each sibling in by hand.

**Excluded on purpose:**
- `Recon` — name-discovery and design document; not part of the
  public API. The recon file still builds and remains on disk, but
  it is not re-exported.

**Notes:**
- `PeriodFunctional` carries one `opaque periodPairing` whose
  implementation is deferred (multi-chart path integration + Stokes
  on manifolds). All other modules are sorry-free.
-/
