import Jacobian.HolomorphicForms.PerronConjugateUniqueness

/-!
# The conjugate-germ étale space

B4 work item W3a (`docs/perron-b4-conjugate-phase0.md`): the carrier and
section topology of the étale space of local-harmonic-conjugate germs over
a charted `X`, with the basis theorem validating the topology choice.

A point of `ConjugateGermSpace X u` is a base point `x` together with the
`Filter.Germ (nhds x) ℝ` class of some local conjugate of `u` near `x`
(`IsLocalConjugateOn`: one uniform witness on an open set — exactly the
shape the W2 bridge `StageHarmonicOnNhd.stageHarmonicOn` produces).  The
topology is generated by the canonical section images; this slice proves
they form a genuine `TopologicalSpace.IsTopologicalBasis`.

W3b adds the étale projection `germProj`, the canonical sections and
their continuity, the section charts
(`germSectionOpenPartialHomeomorph`), and the capstone
`isLocalHomeomorph_germProj`.  Separation and the covering property over
conjugatable loci (where the W1 constant-difference lemmas enter) are W4.
-/

namespace JacobianChallenge.HolomorphicForms

open TopologicalSpace

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]

/-- Section datum for the conjugate-germ space: `v` is a harmonic
conjugate of `u` at every point of the open set `N` (one uniform witness
for the whole set).  This is exactly the shape `StageHarmonicOn` / the W2
bridge produces. -/
def IsLocalConjugateOn (u v : X → ℝ) (N : Set X) : Prop :=
  IsOpen N ∧ ∀ y ∈ N, IsHarmonicConjugateAtReal X u v y

/-- The conjugate-germ étale carrier over `u`: a base point `x` together
with the germ at `x` of some local conjugate of `u`.  Fibers are empty off
the locally-conjugatable locus — intended; the W4 covering statement is
relative to the cut domain. -/
def ConjugateGermSpace (X : Type*) [TopologicalSpace X] [ChartedSpace ℂ X]
    (u : X → ℝ) : Type _ :=
  Σ x : X, {g : Filter.Germ (nhds x) ℝ //
    ∃ v N, IsLocalConjugateOn u v N ∧ x ∈ N ∧
      g = (v : Filter.Germ (nhds x) ℝ)}

/-- The canonical section image over `N` carried by a local conjugate `v`:
the set of germ-space points over `N` whose germ is `v`'s germ. -/
def germSectionImage (u v : X → ℝ) (N : Set X) :
    Set (ConjugateGermSpace X u) :=
  {p | p.1 ∈ N ∧ p.2.1 = (v : Filter.Germ (nhds p.1) ℝ)}

@[simp]
lemma mem_germSectionImage {u v : X → ℝ} {N : Set X}
    {p : ConjugateGermSpace X u} :
    p ∈ germSectionImage u v N ↔
      p.1 ∈ N ∧ p.2.1 = (v : Filter.Germ (nhds p.1) ℝ) :=
  Iff.rfl

/-- The generating family for the étale topology: all canonical section
images over section data. -/
def germSectionBasis (u : X → ℝ) : Set (Set (ConjugateGermSpace X u)) :=
  {S | ∃ v N, IsLocalConjugateOn u v N ∧ S = germSectionImage u v N}

/-- The étale/section topology on the conjugate-germ space. -/
instance conjugateGermSpaceTopologicalSpace (u : X → ℝ) :
    TopologicalSpace (ConjugateGermSpace X u) :=
  generateFrom (germSectionBasis u)

/-- W3a capstone: the canonical section images form a topological basis of
the étale topology.

Covering: every germ-space point lies in the section image of its own
defining datum.  Intersection: if `p` lies in two section images, the germ
equalities give `v =ᶠ[nhds p.1] v'`, so the open set
`interior {v = v'} ∩ N ∩ N'` carries a common smaller section image —
pure germ logic, no conjugate-uniqueness input. -/
theorem isTopologicalBasis_germSectionBasis (u : X → ℝ) :
    IsTopologicalBasis (germSectionBasis u) := by
  refine ⟨?_, ?_, rfl⟩
  · -- exists_subset_inter
    rintro t₁ ⟨v, N, hvN, rfl⟩ t₂ ⟨v', N', hv'N', rfl⟩ p ⟨hp₁, hp₂⟩
    obtain ⟨hpN, hpv⟩ := hp₁
    obtain ⟨hpN', hpv'⟩ := hp₂
    -- The two germs agree at `p.1`, hence the functions agree eventually.
    have hvv' : v =ᶠ[nhds p.1] v' :=
      Filter.Germ.coe_eq.mp (hpv ▸ hpv')
    -- Common refinement: agreement interior ∩ N ∩ N'.
    set N'' : Set X := interior {y : X | v y = v' y} ∩ (N ∩ N') with hN''
    have hN''_open : IsOpen N'' :=
      isOpen_interior.inter (hvN.1.inter hv'N'.1)
    have hpN'' : p.1 ∈ N'' := by
      refine ⟨mem_interior_iff_mem_nhds.mpr ?_, hpN, hpN'⟩
      filter_upwards [hvv'] with y hy
      exact hy
    have hvN'' : IsLocalConjugateOn u v N'' :=
      ⟨hN''_open, fun y hy => hvN.2 y hy.2.1⟩
    refine ⟨germSectionImage u v N'', ⟨v, N'', hvN'', rfl⟩,
      ⟨hpN'', hpv⟩, ?_⟩
    -- The refined image sits inside both originals.
    rintro q ⟨hqN'', hqv⟩
    have hqvv' : v =ᶠ[nhds q.1] v' := by
      filter_upwards [isOpen_interior.mem_nhds hqN''.1] with y hy
      exact (interior_subset hy : y ∈ {y : X | v y = v' y})
    refine ⟨⟨hqN''.2.1, hqv⟩, ⟨hqN''.2.2, ?_⟩⟩
    rw [hqv]
    exact Filter.Germ.coe_eq.mpr hqvv'
  · -- sUnion_eq
    rw [Set.eq_univ_iff_forall]
    intro p
    obtain ⟨v, N, hvN, hpN, hpv⟩ := p.2.2
    exact ⟨germSectionImage u v N, ⟨v, N, hvN, rfl⟩, hpN, hpv⟩

/-- The étale projection of the conjugate-germ space. -/
def germProj (u : X → ℝ) : ConjugateGermSpace X u → X :=
  Sigma.fst

@[simp]
lemma germProj_mk {u : X → ℝ} (x : X)
    (g : {g : Filter.Germ (nhds x) ℝ //
      ∃ v N, IsLocalConjugateOn u v N ∧ x ∈ N ∧
        g = (v : Filter.Germ (nhds x) ℝ)}) :
    germProj u ⟨x, g⟩ = x :=
  rfl

/-- Each canonical section image is open in the étale topology. -/
lemma isOpen_germSectionImage {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) :
    IsOpen (germSectionImage u v N) :=
  (isTopologicalBasis_germSectionBasis u).isOpen ⟨v, N, h, rfl⟩

/-- The étale projection is continuous: the preimage of an open `V` is
covered by the refined section images over `N ∩ V`. -/
lemma continuous_germProj (u : X → ℝ) : Continuous (germProj u) := by
  rw [continuous_def]
  intro V hV
  rw [isOpen_iff_mem_nhds]
  intro p hp
  obtain ⟨v, N, hvN, hpN, hpv⟩ := p.2.2
  have hsub : IsLocalConjugateOn u v (N ∩ V) :=
    ⟨hvN.1.inter hV, fun y hy => hvN.2 y hy.1⟩
  refine Filter.mem_of_superset
    ((isOpen_germSectionImage hsub).mem_nhds ⟨⟨hpN, hp⟩, hpv⟩) ?_
  rintro q ⟨⟨_, hqV⟩, _⟩
  exact hqV

/-- The canonical section point over `y ∈ N` carried by a section datum. -/
def germSection {u v : X → ℝ} {N : Set X} (h : IsLocalConjugateOn u v N)
    {y : X} (hy : y ∈ N) : ConjugateGermSpace X u :=
  ⟨y, ⟨(v : Filter.Germ (nhds y) ℝ), v, N, h, hy, rfl⟩⟩

@[simp]
lemma germProj_germSection {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) {y : X} (hy : y ∈ N) :
    germProj u (germSection h hy) = y :=
  rfl

@[simp]
lemma germSection_mem_germSectionImage {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) {y : X} (hy : y ∈ N) :
    germSection h hy ∈ germSectionImage u v N :=
  ⟨hy, rfl⟩

open Classical in
/-- Total inverse function for the section chart: the canonical section on
`N`, an arbitrary basepoint `e` elsewhere (fibers may be empty off the
conjugatable locus, so a junk value must be supplied, not conjured). -/
noncomputable def germSectionFun {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) (e : ConjugateGermSpace X u) :
    X → ConjugateGermSpace X u :=
  fun y => if hy : y ∈ N then germSection h hy else e

lemma germSectionFun_of_mem {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) (e : ConjugateGermSpace X u)
    {y : X} (hy : y ∈ N) :
    germSectionFun h e y = germSection h hy := by
  unfold germSectionFun
  exact dif_pos hy

/-- The section is continuous on `N`: if the section point at `y₀` lies in
a basic open carried by `(v', N')`, the germs of `v, v'` agree at `y₀`, so
the section maps the open set `interior {v = v'} ∩ N ∩ N'` into that basic
open — the same germ-refinement move as the W3a basis theorem. -/
lemma continuousOn_germSectionFun {u v : X → ℝ} {N : Set X}
    (h : IsLocalConjugateOn u v N) (e : ConjugateGermSpace X u) :
    ContinuousOn (germSectionFun h e) N := by
  intro y₀ hy₀
  refine ContinuousAt.continuousWithinAt ?_
  have hb := (isTopologicalBasis_germSectionBasis u).nhds_hasBasis
    (a := germSectionFun h e y₀)
  rw [ContinuousAt, hb.tendsto_right_iff]
  rintro S ⟨⟨v', N', hv'N', rfl⟩, hmem⟩
  rw [germSectionFun_of_mem h e hy₀] at hmem
  obtain ⟨hy₀N', hgerm⟩ := hmem
  -- The two carrier germs agree at y₀.
  have hvv' : v =ᶠ[nhds y₀] v' := Filter.Germ.coe_eq.mp hgerm
  set W : Set X := interior {y : X | v y = v' y} ∩ (N ∩ N') with hW
  have hW_open : IsOpen W := isOpen_interior.inter (h.1.inter hv'N'.1)
  have hy₀W : y₀ ∈ W := by
    refine ⟨mem_interior_iff_mem_nhds.mpr ?_, hy₀, hy₀N'⟩
    filter_upwards [hvv'] with y hy
    exact hy
  filter_upwards [hW_open.mem_nhds hy₀W] with y hyW
  rw [germSectionFun_of_mem h e hyW.2.1]
  refine ⟨hyW.2.2, ?_⟩
  -- The germ of `v` at `y` equals the germ of `v'` at `y`.
  refine Filter.Germ.coe_eq.mpr ?_
  filter_upwards [isOpen_interior.mem_nhds hyW.1] with z hz
  exact (interior_subset hz : z ∈ {z : X | v z = v' z})

/-- The section chart of the étale projection: a homeomorphism between the
section image carried by `(v, N)` and `N`, with the projection as forward
map and the canonical section (junk basepoint `e` off `N`) as inverse. -/
noncomputable def germSectionOpenPartialHomeomorph {u v : X → ℝ}
    {N : Set X} (h : IsLocalConjugateOn u v N)
    (e : ConjugateGermSpace X u) :
    OpenPartialHomeomorph (ConjugateGermSpace X u) X where
  toFun := germProj u
  invFun := germSectionFun h e
  source := germSectionImage u v N
  target := N
  map_source' := fun _ hp => hp.1
  map_target' := fun y hy => by
    rw [germSectionFun_of_mem h e hy]
    exact germSection_mem_germSectionImage h hy
  left_inv' := by
    rintro ⟨x, gval, gprop⟩ ⟨hxN, hgv⟩
    show germSectionFun h e x = _
    rw [germSectionFun_of_mem h e hxN]
    show (⟨x, ⟨(v : Filter.Germ (nhds x) ℝ), v, N, h, hxN, rfl⟩⟩ :
      ConjugateGermSpace X u) = ⟨x, ⟨gval, gprop⟩⟩
    congr 1
    exact Subtype.ext hgv.symm
  right_inv' := fun y hy => by
    rw [germSectionFun_of_mem h e hy]
    rfl
  open_source := isOpen_germSectionImage h
  open_target := h.1
  continuousOn_toFun := (continuous_germProj u).continuousOn
  continuousOn_invFun := continuousOn_germSectionFun h e

/-- W3b capstone: the étale projection of the conjugate-germ space is a
local homeomorphism — every carrier point carries its defining section
datum, which provides the section chart around it. -/
theorem isLocalHomeomorph_germProj (u : X → ℝ) :
    IsLocalHomeomorph (germProj u) := by
  intro p
  obtain ⟨v, N, hvN, hpN, hpv⟩ := p.2.2
  exact ⟨germSectionOpenPartialHomeomorph hvN p, ⟨hpN, hpv⟩, rfl⟩

end JacobianChallenge.HolomorphicForms
