import Jacobian.HolomorphicForms.PerronConjugateUniqueness

/-!
# The conjugate-germ étale space

B4 work item W3a (`docs/perron-b4-conjugate-phase0.md`): the carrier and
section topology of the étale space of local-harmonic-conjugate germs over
a charted `X`, with the basis theorem validating the topology choice.

A point of `ConjugateGermSpace X u` is a base point `x` together with the
`Filter.Germ (nhds x) ℝ` class of some local conjugate of `u` near `x`
(`IsLocalConjugateOn`: one uniform witness on an open set — exactly the
shape the W2 bridge `StageHarmonicOnNhd.stageHarmonicOn` produces).  The
topology is generated by the canonical section images; this slice proves
they form a genuine `TopologicalSpace.IsTopologicalBasis`.

Projection/`IsLocalHomeomorph` are W3b; separation and the covering
property over conjugatable loci (where the W1 constant-difference lemmas
enter) are W4.
-/

namespace JacobianChallenge.HolomorphicForms

open TopologicalSpace

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]

/-- Section datum for the conjugate-germ space: `v` is a harmonic
conjugate of `u` at every point of the open set `N` (one uniform witness
for the whole set).  This is exactly the shape `StageHarmonicOn` / the W2
bridge produces. -/
def IsLocalConjugateOn (u v : X → ℝ) (N : Set X) : Prop :=
  IsOpen N ∧ ∀ y ∈ N, IsHarmonicConjugateAtReal X u v y

/-- The conjugate-germ étale carrier over `u`: a base point `x` together
with the germ at `x` of some local conjugate of `u`.  Fibers are empty off
the locally-conjugatable locus — intended; the W4 covering statement is
relative to the cut domain. -/
def ConjugateGermSpace (X : Type*) [TopologicalSpace X] [ChartedSpace ℂ X]
    (u : X → ℝ) : Type _ :=
  Σ x : X, {g : Filter.Germ (nhds x) ℝ //
    ∃ v N, IsLocalConjugateOn u v N ∧ x ∈ N ∧
      g = (v : Filter.Germ (nhds x) ℝ)}

/-- The canonical section image over `N` carried by a local conjugate `v`:
the set of germ-space points over `N` whose germ is `v`'s germ. -/
def germSectionImage (u v : X → ℝ) (N : Set X) :
    Set (ConjugateGermSpace X u) :=
  {p | p.1 ∈ N ∧ p.2.1 = (v : Filter.Germ (nhds p.1) ℝ)}

@[simp]
lemma mem_germSectionImage {u v : X → ℝ} {N : Set X}
    {p : ConjugateGermSpace X u} :
    p ∈ germSectionImage u v N ↔
      p.1 ∈ N ∧ p.2.1 = (v : Filter.Germ (nhds p.1) ℝ) :=
  Iff.rfl

/-- The generating family for the étale topology: all canonical section
images over section data. -/
def germSectionBasis (u : X → ℝ) : Set (Set (ConjugateGermSpace X u)) :=
  {S | ∃ v N, IsLocalConjugateOn u v N ∧ S = germSectionImage u v N}

/-- The étale/section topology on the conjugate-germ space. -/
instance conjugateGermSpaceTopologicalSpace (u : X → ℝ) :
    TopologicalSpace (ConjugateGermSpace X u) :=
  generateFrom (germSectionBasis u)

/-- W3a capstone: the canonical section images form a topological basis of
the étale topology.

Covering: every germ-space point lies in the section image of its own
defining datum.  Intersection: if `p` lies in two section images, the germ
equalities give `v =ᶠ[nhds p.1] v'`, so the open set
`interior {v = v'} ∩ N ∩ N'` carries a common smaller section image —
pure germ logic, no conjugate-uniqueness input. -/
theorem isTopologicalBasis_germSectionBasis (u : X → ℝ) :
    IsTopologicalBasis (germSectionBasis u) := by
  refine ⟨?_, ?_, rfl⟩
  · -- exists_subset_inter
    rintro t₁ ⟨v, N, hvN, rfl⟩ t₂ ⟨v', N', hv'N', rfl⟩ p ⟨hp₁, hp₂⟩
    obtain ⟨hpN, hpv⟩ := hp₁
    obtain ⟨hpN', hpv'⟩ := hp₂
    -- The two germs agree at `p.1`, hence the functions agree eventually.
    have hvv' : v =ᶠ[nhds p.1] v' :=
      Filter.Germ.coe_eq.mp (hpv ▸ hpv')
    -- Common refinement: agreement interior ∩ N ∩ N'.
    set N'' : Set X := interior {y : X | v y = v' y} ∩ (N ∩ N') with hN''
    have hN''_open : IsOpen N'' :=
      isOpen_interior.inter (hvN.1.inter hv'N'.1)
    have hpN'' : p.1 ∈ N'' := by
      refine ⟨mem_interior_iff_mem_nhds.mpr ?_, hpN, hpN'⟩
      filter_upwards [hvv'] with y hy
      exact hy
    have hvN'' : IsLocalConjugateOn u v N'' :=
      ⟨hN''_open, fun y hy => hvN.2 y hy.2.1⟩
    refine ⟨germSectionImage u v N'', ⟨v, N'', hvN'', rfl⟩,
      ⟨hpN'', hpv⟩, ?_⟩
    -- The refined image sits inside both originals.
    rintro q ⟨hqN'', hqv⟩
    have hqvv' : v =ᶠ[nhds q.1] v' := by
      filter_upwards [isOpen_interior.mem_nhds hqN''.1] with y hy
      exact (interior_subset hy : y ∈ {y : X | v y = v' y})
    refine ⟨⟨hqN''.2.1, hqv⟩, ⟨hqN''.2.2, ?_⟩⟩
    rw [hqv]
    exact Filter.Germ.coe_eq.mpr hqvv'
  · -- sUnion_eq
    rw [Set.eq_univ_iff_forall]
    intro p
    obtain ⟨v, N, hvN, hpN, hpv⟩ := p.2.2
    exact ⟨germSectionImage u v N, ⟨v, N, hvN, rfl⟩, hpN, hpv⟩

end JacobianChallenge.HolomorphicForms
